2025-08-28 20:55:19,883 - ModelManager - INFO - Initializing models...
2025-08-28 21:00:14,426 - ModelManager - ERROR - Error initializing models: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /openai/clip-vit-large-patch14/resolve/main/model.safetensors (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001CA2852DE20>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: d26f029a-f64a-490f-92ce-f81d8e7385d7)')
2025-08-28 21:01:03,629 - ModelManager - INFO - Initializing models...
2025-08-28 21:08:27,907 - VideoGenerator - INFO - Using device: cpu
2025-08-28 21:08:27,907 - VideoGenerator - INFO - Loading Stable Video Diffusion pipeline...
2025-08-28 22:09:06,166 - VideoGenerator - INFO - Pipeline loaded successfully
2025-08-28 22:09:06,166 - ModelManager - INFO - All models initialized successfully
2025-08-28 22:15:30,878 - ModelManager - INFO - Starting complete video generation pipeline...
2025-08-28 22:15:30,920 - VideoGenerator - INFO - Starting video generation...
2025-08-28 22:18:30,829 - VideoGenerator - ERROR - Error during video generation: [enforce fail at alloc_cpu.cpp:121] data. DefaultCPUAllocator: not enough memory: you tried to allocate 2150400000 bytes.
2025-08-28 22:18:30,899 - ModelManager - ERROR - Pipeline error: [enforce fail at alloc_cpu.cpp:121] data. DefaultCPUAllocator: not enough memory: you tried to allocate 2150400000 bytes.
